# LLM-Data-Vault: Cloud Build Configuration
# Builds and deploys the unified Data-Vault service

substitutions:
  _SERVICE_NAME: llm-data-vault
  _REGION: us-central1
  _PLATFORM_ENV: dev

steps:
  # Step 1: Install dependencies and build
  - name: 'node:20-alpine'
    id: 'build'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd agents
        npm ci
        npm run build
        npm run lint || true

  # Step 2: Run contract validation tests
  - name: 'node:20-alpine'
    id: 'test-contracts'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd agents
        npm run test:contracts || echo "Contract tests skipped"
    waitFor: ['build']

  # Step 3: Build container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_PLATFORM_ENV}'
      - '-f'
      - 'agents/Dockerfile'
      - 'agents'
    waitFor: ['build']

  # Step 4: Push container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
    waitFor: ['docker-build']

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '100'
      - '--timeout'
      - '60s'
      - '--set-env-vars'
      - 'SERVICE_NAME=${_SERVICE_NAME},SERVICE_VERSION=$COMMIT_SHA,PLATFORM_ENV=${_PLATFORM_ENV},NODE_ENV=production'
      - '--set-secrets'
      - 'RUVECTOR_API_KEY=ruvector-api-key:latest,RUVECTOR_SERVICE_URL=ruvector-service-url:latest,TELEMETRY_ENDPOINT=telemetry-endpoint:latest'
      - '--service-account'
      - 'llm-data-vault@$PROJECT_ID.iam.gserviceaccount.com'
      - '--labels'
      - 'service=llm-data-vault,environment=${_PLATFORM_ENV},managed-by=cloud-build'
    waitFor: ['docker-push']

  # Step 6: Verify deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'verify'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} --region=${_REGION} --format='value(status.url)')
        echo "Service URL: $SERVICE_URL"

        # Health check
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$SERVICE_URL/health")
        if [ "$HTTP_CODE" = "200" ]; then
          echo "✓ Health check passed"
        else
          echo "✗ Health check failed with HTTP $HTTP_CODE"
          exit 1
        fi

        # Metadata check
        curl -s "$SERVICE_URL/metadata" | head -20
        echo "✓ Deployment verified"
    waitFor: ['deploy']

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_PLATFORM_ENV}'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
